[package]
name = "vcard-compact"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
logos = "0.12"
language-tags = "0.3"
fluent-uri = "0.1"
time = "0.3"

[dev-dependencies]
anyhow = "1"
