extend= [
  { path = "coverage_grcov.makefile.toml" }
]

[env]
RUST_BACKTRACE = 0

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.docs]
command = "cargo"
args = ["doc", "--open", "--no-deps"]

[tasks.unit]
command = "cargo"
args = ["test", "--lib", "--", "--nocapture"]

[tasks.integration]
command = "cargo"
args = ["test"]

[tasks.test]
dependencies = ["unit", "integration"]

[tasks.dev]
dependencies = ["check-wasm", "test", "format", "clippy"]

[tasks.check-wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.genhtml]
script = '''
grcov . --source-dir src --binary-path ./target/debug -t html --branch --ignore-not-existing -o ./target/coverage/ --ignore 'tests/*' --ignore 'target/*'
'''

[tasks.coverage]
alias = "coverage_grcov"

[tasks.cover]
dependencies = ["build", "coverage", "genhtml"]
